/*
 * RobotMap.cpp
 *
 *  Created on: Jan 15, 2016
 *      Author: RoboGym
 */
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


#include <iostream>

std::shared_ptr<Talon> RobotMap::driveSubsystemTalon1;
std::shared_ptr<Talon> RobotMap::driveSubsystemTalon2;
std::shared_ptr<Talon> RobotMap::driveSubsystemTalon3;
std::shared_ptr<Talon> RobotMap::driveSubsystemTalon4;
std::shared_ptr<RobotDrive> RobotMap::driveSubsystemRobotDrive41;
std::shared_ptr<AHRS> RobotMap::ahrs;


void RobotMap::init(){
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    driveSubsystemTalon1.reset(new Talon(0));
    lw->AddActuator("DriveSubsystem", "Talon 1", driveSubsystemTalon1);

    driveSubsystemTalon2.reset(new Talon(1));
    lw->AddActuator("DriveSubsystem", "Talon 2", driveSubsystemTalon2);

    driveSubsystemTalon3.reset(new Talon(2));
    lw->AddActuator("DriveSubsystem", "Talon 3", driveSubsystemTalon3);

    driveSubsystemTalon4.reset(new Talon(3));
    lw->AddActuator("DriveSubsystem", "Talon 4", driveSubsystemTalon4);

    driveSubsystemRobotDrive41.reset(new RobotDrive(driveSubsystemTalon1, driveSubsystemTalon2,
              driveSubsystemTalon3, driveSubsystemTalon4));

    /* Communicate w/navX MXP via the MXP SPI Bus.                                       */
     /* Alternatively:  I2C::Port::kMXP, SerialPort::Port::kMXP or SerialPort::Port::kUSB */
     /* See http://navx-mxp.kauailabs.com/guidance/selecting-an-interface/ for details.   */
     ahrs.reset(new AHRS(SPI::Port::kMXP));

}


